<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

/**
 * Full-site editable content. Every visible string on the home, funding,
 * intake and onboarding pages, wired to cms() in the Blade templates.
 *
 * text/textarea values are stored entity-decoded because they render through
 * Blade's escaped {{ }}; html values are stored raw because they render through
 * {!! !!}. Existing rows are never overwritten (owner edits are preserved).
 */
class PageContentSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [

            // ============================================================
            // HOME PAGE
            // ============================================================
            ['home.extra.nav_services', 'Services', 'text', 'home_extra', 'Nav — Services link'],
            ['home.extra.nav_pricing', 'Pricing', 'text', 'home_extra', 'Nav — Pricing link'],
            ['home.extra.nav_mentorship', 'Mentorship', 'text', 'home_extra', 'Nav — Mentorship link'],
            ['home.extra.nav_business', 'Business Setup', 'text', 'home_extra', 'Nav — Business Setup link'],
            ['home.extra.nav_funding', 'Funding', 'text', 'home_extra', 'Nav — Funding link'],
            ['home.extra.nav_faq', 'FAQ', 'text', 'home_extra', 'Nav — FAQ link'],
            ['home.extra.marquee1', 'From Knowledge to Wisdom', 'text', 'home_extra', 'Marquee phrase 1'],
            ['home.extra.marquee2', 'From Wisdom to Wealth', 'text', 'home_extra', 'Marquee phrase 2'],
            ['home.extra.marquee3', 'Repair · Rebuild · Structure · Fund', 'text', 'home_extra', 'Marquee phrase 3'],
            ['home.extra.marquee4', 'Built for the Next Generation', 'text', 'home_extra', 'Marquee phrase 4'],

            ['home.services.eyebrow', 'What We Do', 'text', 'home_services', 'Services — eyebrow'],
            ['home.services.heading', 'Five pillars to build, protect, and leverage your wealth.', 'text', 'home_services', 'Services — section heading'],
            ['home.services.sub', 'Cleaning up your credit, building business credit, or trying to get funded for the first time. You get the structure, the teaching, and the work done with you so you can move forward with confidence.', 'textarea', 'home_services', 'Services — section subtitle'],
            ['home.services.card1_title', 'Credit Repair', 'text', 'home_services', 'Services — card 1 title'],
            ['home.services.card1_desc', 'Disputes, deletions, and strategy to remove negative items and lift your score quickly.', 'textarea', 'home_services', 'Services — card 1 description'],
            ['home.services.card2_title', 'Rebuilding Credit', 'text', 'home_services', 'Services — card 2 title'],
            ['home.services.card2_desc', 'Tradelines, utilization strategy, and credit mix done right so your score holds and grows.', 'textarea', 'home_services', 'Services — card 2 description'],
            ['home.services.card3_title', 'Business Structure', 'text', 'home_services', 'Services — card 3 title'],
            ['home.services.card3_desc', 'LLC formation, EIN, bank accounts, and compliance, all set up so lenders take you seriously.', 'textarea', 'home_services', 'Services — card 3 description'],
            ['home.services.card4_title', 'Business Credit', 'text', 'home_services', 'Services — card 4 title'],
            ['home.services.card4_desc', 'Establish Dun & Bradstreet, vendor accounts, and trade lines to unlock real corporate credit.', 'textarea', 'home_services', 'Services — card 4 description'],
            ['home.services.card5_title', 'Personal & Business Funding', 'text', 'home_services', 'Services — card 5 title'],
            ['home.services.card5_desc', 'Personal lines, business lines of credit, and capital placement, stacked the smart way.', 'textarea', 'home_services', 'Services — card 5 description'],
            ['home.services.card6_title', 'Wealth University', 'text', 'home_services', 'Services — card 6 title'],
            ['home.services.card6_desc', 'Live trainings, replays, frameworks, and a community of people moving in the same direction as you.', 'textarea', 'home_services', 'Services — card 6 description'],

            ['home.reviews.video_eyebrow', 'Real Client Stories', 'text', 'home_reviews', 'Video reviews — eyebrow'],
            ['home.reviews.video_heading', 'Hear it straight from <span class="gold-text">our clients.</span>', 'html', 'home_reviews', 'Video reviews — heading'],
            ['home.reviews.video_sub', 'Real people, real results. Tap a video to watch their journey.', 'text', 'home_reviews', 'Video reviews — subtitle'],
            ['home.reviews.video_badge', 'Video Review', 'text', 'home_reviews', 'Video reviews — card badge'],
            ['home.reviews.video_card_name', 'Real Client Story', 'text', 'home_reviews', 'Video reviews — card name'],
            ['home.reviews.video_card_meta', 'Tap to play', 'text', 'home_reviews', 'Video reviews — card meta'],

            ['home.extra.factors_eyebrow', 'Real Problems', 'text', 'home_extra', 'Factors — eyebrow'],
            ['home.extra.factors_heading', '5 Common Factors<br/><span class="gold-text">That Can Hurt Your Credit</span>', 'html', 'home_extra', 'Factors — heading'],
            ['home.extra.factors_sub', 'Your credit report can carry damaging items that drag your score down for years. Each of the five below can be identified, verified, and often removed under federal consumer protection law.', 'textarea', 'home_extra', 'Factors — intro paragraph'],
            ['home.extra.factors_law', 'We help clients review their reports and challenge items that may be inaccurate, incomplete, or unverifiable under the <strong class="text-gold-300">Fair Credit Reporting Act</strong> and <strong class="text-gold-300">Fair Debt Collection Practices Act</strong>.', 'html', 'home_extra', 'Factors — legal paragraph'],
            ['home.extra.factors_cta', 'Schedule a Credit Review →', 'text', 'home_extra', 'Factors — CTA button'],
            ['home.extra.factor1_legal', 'FCRA §611', 'text', 'home_extra', 'Factor 1 — legal badge'],
            ['home.extra.factor1_title', 'Late Payments', 'text', 'home_extra', 'Factor 1 — title'],
            ['home.extra.factor1_desc', '30, 60, or 90-day late marks that quietly erode your payment history for up to seven years. Single biggest drag on your FICO score.', 'textarea', 'home_extra', 'Factor 1 — description'],
            ['home.extra.factor1_impact_label', 'FICO Score Weight', 'text', 'home_extra', 'Factor 1 — impact label'],
            ['home.extra.factor1_impact_pct', '35%', 'text', 'home_extra', 'Factor 1 — impact value'],
            ['home.extra.factor1_stat1_num', '42%', 'text', 'home_extra', 'Factor 1 — stat 1 number'],
            ['home.extra.factor1_stat1_label', 'Reports affected', 'text', 'home_extra', 'Factor 1 — stat 1 label'],
            ['home.extra.factor1_stat2_num', '30–60d', 'text', 'home_extra', 'Factor 1 — stat 2 number'],
            ['home.extra.factor1_stat2_label', 'Avg. removal', 'text', 'home_extra', 'Factor 1 — stat 2 label'],
            ['home.extra.factor2_legal', 'FDCPA §809', 'text', 'home_extra', 'Factor 2 — legal badge'],
            ['home.extra.factor2_title', 'Collections', 'text', 'home_extra', 'Factor 2 — title'],
            ['home.extra.factor2_desc', 'Third-party collection accounts appear as serious derogatory marks. Many are disputable under federal debt collection law.', 'textarea', 'home_extra', 'Factor 2 — description'],
            ['home.extra.factor2_impact_label', 'Score Damage Potential', 'text', 'home_extra', 'Factor 2 — impact label'],
            ['home.extra.factor2_impact_pct', 'High', 'text', 'home_extra', 'Factor 2 — impact value'],
            ['home.extra.factor2_stat1_num', '28%', 'text', 'home_extra', 'Factor 2 — stat 1 number'],
            ['home.extra.factor2_stat1_label', 'Reports affected', 'text', 'home_extra', 'Factor 2 — stat 1 label'],
            ['home.extra.factor2_stat2_num', '14–45d', 'text', 'home_extra', 'Factor 2 — stat 2 number'],
            ['home.extra.factor2_stat2_label', 'Avg. removal', 'text', 'home_extra', 'Factor 2 — stat 2 label'],
            ['home.extra.factor3_legal', 'FCRA §611', 'text', 'home_extra', 'Factor 3 — legal badge'],
            ['home.extra.factor3_title', 'Charge-Offs', 'text', 'home_extra', 'Factor 3 — title'],
            ['home.extra.factor3_desc', 'The lender wrote the account off as a loss, but it still reports against you. Often challengeable if data is incomplete or inaccurate.', 'textarea', 'home_extra', 'Factor 3 — description'],
            ['home.extra.factor3_impact_label', 'Score Damage Potential', 'text', 'home_extra', 'Factor 3 — impact label'],
            ['home.extra.factor3_impact_pct', 'High', 'text', 'home_extra', 'Factor 3 — impact value'],
            ['home.extra.factor3_stat1_num', '19%', 'text', 'home_extra', 'Factor 3 — stat 1 number'],
            ['home.extra.factor3_stat1_label', 'Reports affected', 'text', 'home_extra', 'Factor 3 — stat 1 label'],
            ['home.extra.factor3_stat2_num', '30–75d', 'text', 'home_extra', 'Factor 3 — stat 2 number'],
            ['home.extra.factor3_stat2_label', 'Avg. removal', 'text', 'home_extra', 'Factor 3 — stat 2 label'],
            ['home.extra.factor4_legal', 'Strategy', 'text', 'home_extra', 'Factor 4 — legal badge'],
            ['home.extra.factor4_title', 'High Utilization', 'text', 'home_extra', 'Factor 4 — title'],
            ['home.extra.factor4_desc', 'Balances near your credit limits. Reducing utilization is often the single fastest score lift available, sometimes in one billing cycle.', 'textarea', 'home_extra', 'Factor 4 — description'],
            ['home.extra.factor4_impact_label', 'FICO Score Weight', 'text', 'home_extra', 'Factor 4 — impact label'],
            ['home.extra.factor4_impact_pct', '30%', 'text', 'home_extra', 'Factor 4 — impact value'],
            ['home.extra.factor4_stat1_num', '61%', 'text', 'home_extra', 'Factor 4 — stat 1 number'],
            ['home.extra.factor4_stat1_label', 'Of cardholders', 'text', 'home_extra', 'Factor 4 — stat 1 label'],
            ['home.extra.factor4_stat2_num', '&lt;30d', 'html', 'home_extra', 'Factor 4 — stat 2 number'],
            ['home.extra.factor4_stat2_label', 'To rebalance', 'text', 'home_extra', 'Factor 4 — stat 2 label'],
            ['home.extra.factor5_legal', 'FCRA §605', 'text', 'home_extra', 'Factor 5 — legal badge'],
            ['home.extra.factor5_title', 'Public Records', 'text', 'home_extra', 'Factor 5 — title'],
            ['home.extra.factor5_desc', 'Bankruptcies, tax liens, and civil judgments can linger seven to ten years. Many are removable once the statute window closes.', 'textarea', 'home_extra', 'Factor 5 — description'],
            ['home.extra.factor5_impact_label', 'Score Damage Potential', 'text', 'home_extra', 'Factor 5 — impact label'],
            ['home.extra.factor5_impact_pct', 'Severe', 'text', 'home_extra', 'Factor 5 — impact value'],
            ['home.extra.factor5_stat1_num', '11%', 'text', 'home_extra', 'Factor 5 — stat 1 number'],
            ['home.extra.factor5_stat1_label', 'Reports affected', 'text', 'home_extra', 'Factor 5 — stat 1 label'],
            ['home.extra.factor5_stat2_num', '45–90d', 'text', 'home_extra', 'Factor 5 — stat 2 number'],
            ['home.extra.factor5_stat2_label', 'Avg. removal', 'text', 'home_extra', 'Factor 5 — stat 2 label'],
            ['home.extra.factors_stat_num', '9 in 10', 'text', 'home_extra', 'Factors — stat banner number'],
            ['home.extra.factors_stat_text', 'credit reports we review contain at least one inaccurate, outdated, or unverifiable item.', 'textarea', 'home_extra', 'Factors — stat banner text'],
            ['home.extra.factors_meta1_num', '15 U.S.C.', 'text', 'home_extra', 'Factors — meta strip 1 number'],
            ['home.extra.factors_meta1_text', '§1681 · Fair Credit Reporting Act', 'text', 'home_extra', 'Factors — meta strip 1 text'],
            ['home.extra.factors_meta2_num', '15 U.S.C.', 'text', 'home_extra', 'Factors — meta strip 2 number'],
            ['home.extra.factors_meta2_text', '§1692 · Fair Debt Collection Practices Act', 'text', 'home_extra', 'Factors — meta strip 2 text'],
            ['home.extra.factors_meta3_num', '100%', 'text', 'home_extra', 'Factors — meta strip 3 number'],
            ['home.extra.factors_meta3_text', 'Within federal consumer protection law', 'text', 'home_extra', 'Factors — meta strip 3 text'],

            ['home.extra.pricing_eyebrow', 'Pricing', 'text', 'home_extra', 'Pricing — eyebrow'],
            ['home.extra.pricing_heading', 'Choose your path to financial freedom.', 'text', 'home_extra', 'Pricing — heading'],
            ['home.extra.pricing_sub', 'Honest pricing. No fluff. Pick the package that fits where you are right now, and you can always upgrade later.', 'textarea', 'home_extra', 'Pricing — subtitle'],
            ['home.extra.bnpl_label', 'Pay Over Time &mdash; 4 interest-free payments', 'html', 'home_extra', 'Pricing — BNPL label'],
            ['home.extra.bnpl_checkout', 'at checkout', 'text', 'home_extra', 'Pricing — BNPL "at checkout"'],
            ['home.extra.community_eyebrow', 'Monthly Community', 'text', 'home_extra', 'Pricing — community eyebrow'],
            ['home.extra.community_title', 'Skool Community Access', 'text', 'home_extra', 'Pricing — community title'],
            ['home.extra.community_desc', 'Weekly trainings, frameworks, replays, and the AQ Wealth network. Month to month, no contracts.', 'textarea', 'home_extra', 'Pricing — community description'],
            ['home.extra.community_price', '$99<span class="text-lg align-top ml-1 text-gold-200">/mo</span>', 'html', 'home_extra', 'Pricing — community price'],
            ['home.extra.packages_heading', 'Credit Repair Packages', 'text', 'home_extra', 'Pricing — packages heading'],
            ['home.extra.packages_sub', 'Every package shows two prices: a <strong>Single</strong> price for just you, and a discounted <strong>Duo</strong> price when you bring a partner along. Both are visible on every card so you always know what you\'re paying.', 'html', 'home_extra', 'Pricing — packages subtitle'],
            ['home.extra.tier_single_name', 'Single', 'text', 'home_extra', 'Pricing — Single tier name'],
            ['home.extra.tier_single_meta', 'Just for you · one-time', 'text', 'home_extra', 'Pricing — Single tier meta'],
            ['home.extra.tier_duo_name', 'Duo', 'text', 'home_extra', 'Pricing — Duo tier name'],
            ['home.extra.tier_duo_meta', 'You + a partner · one-time', 'text', 'home_extra', 'Pricing — Duo tier meta'],
            ['home.extra.price_includes_label', 'What\'s included', 'text', 'home_extra', 'Pricing — "What\'s included" label'],
            ['home.extra.price_standard_label', 'Standard', 'text', 'home_extra', 'Pricing — Standard tier label'],
            ['home.extra.price_standard_time', 'Results in 30–90 days', 'text', 'home_extra', 'Pricing — Standard time pill'],
            ['home.extra.price_standard_save', 'Save $399', 'text', 'home_extra', 'Pricing — Standard Duo save'],
            ['home.extra.price_standard_feat1', '3 dispute rounds across all 3 bureaus', 'text', 'home_extra', 'Pricing — Standard feature 1'],
            ['home.extra.price_standard_feat2', 'Personalized strategy & action plan', 'text', 'home_extra', 'Pricing — Standard feature 2'],
            ['home.extra.price_standard_feat3', 'Removal of inaccurate negatives', 'text', 'home_extra', 'Pricing — Standard feature 3'],
            ['home.extra.price_standard_feat4', 'Score-building guidance', 'text', 'home_extra', 'Pricing — Standard feature 4'],
            ['home.extra.price_standard_cta', 'Get Started →', 'text', 'home_extra', 'Pricing — Standard CTA'],
            ['home.extra.price_expedited_ribbon', 'Most Popular', 'text', 'home_extra', 'Pricing — Expedited ribbon'],
            ['home.extra.price_expedited_label', 'Expedited', 'text', 'home_extra', 'Pricing — Expedited tier label'],
            ['home.extra.price_expedited_time', 'Fast-track 14–30 days', 'text', 'home_extra', 'Pricing — Expedited time pill'],
            ['home.extra.price_expedited_save', 'Save $799', 'text', 'home_extra', 'Pricing — Expedited Duo save'],
            ['home.extra.price_expedited_feat1', 'Priority dispute processing', 'text', 'home_extra', 'Pricing — Expedited feature 1'],
            ['home.extra.price_expedited_feat2', 'Aggressive bureau response cycle', 'text', 'home_extra', 'Pricing — Expedited feature 2'],
            ['home.extra.price_expedited_feat3', 'All Standard plan benefits', 'text', 'home_extra', 'Pricing — Expedited feature 3'],
            ['home.extra.price_expedited_feat4', 'Direct messaging with our team', 'text', 'home_extra', 'Pricing — Expedited feature 4'],
            ['home.extra.price_expedited_cta', 'Choose Expedited', 'text', 'home_extra', 'Pricing — Expedited CTA'],
            ['home.extra.price_premium_label', 'Premium', 'text', 'home_extra', 'Pricing — Premium tier label'],
            ['home.extra.price_premium_time', 'Done-for-you · until clean', 'text', 'home_extra', 'Pricing — Premium time pill'],
            ['home.extra.price_premium_save', 'Save $1,199', 'text', 'home_extra', 'Pricing — Premium Duo save'],
            ['home.extra.price_premium_feat1', 'Unlimited dispute rounds until done', 'text', 'home_extra', 'Pricing — Premium feature 1'],
            ['home.extra.price_premium_feat2', 'Full credit profile rebuild', 'text', 'home_extra', 'Pricing — Premium feature 2'],
            ['home.extra.price_premium_feat3', 'Tradeline & utilization strategy', 'text', 'home_extra', 'Pricing — Premium feature 3'],
            ['home.extra.price_premium_feat4', 'Lifetime credit education access', 'text', 'home_extra', 'Pricing — Premium feature 4'],
            ['home.extra.price_premium_cta', 'Go Premium →', 'text', 'home_extra', 'Pricing — Premium CTA'],
            ['home.extra.founder_pill', 'Meet the Founder', 'text', 'home_extra', 'Founder — pill label'],

            ['home.reviews.results_eyebrow', 'Real Results', 'text', 'home_reviews', 'Results — eyebrow'],
            ['home.reviews.results_heading', 'Wins worth talking about.', 'text', 'home_reviews', 'Results — heading'],
            ['home.reviews.results_sub', 'From scores in the 400s to home approvals, business funding, and clean reports. These are real lifts in real timelines.', 'textarea', 'home_reviews', 'Results — subtitle'],
            ['home.reviews.verified_badge', 'Verified', 'text', 'home_reviews', 'Reviews — Verified badge'],
            ['home.reviews.label_before', 'Before', 'text', 'home_reviews', 'Results — Before label'],
            ['home.reviews.label_after', 'After', 'text', 'home_reviews', 'Results — After label'],
            ['home.reviews.result1_emoji', '🏡', 'text', 'home_reviews', 'Result 1 — emoji'],
            ['home.reviews.result1_quote', 'Approved for our first home after years of being denied. Closed at 6.4% APR. Felt like a dream.', 'textarea', 'home_reviews', 'Result 1 — quote'],
            ['home.reviews.result1_initials', 'JR', 'text', 'home_reviews', 'Result 1 — initials'],
            ['home.reviews.result1_name', 'Jasmine R.', 'text', 'home_reviews', 'Result 1 — name'],
            ['home.reviews.result1_loc', 'Charlotte, NC · Full Repair + Mortgage Prep', 'text', 'home_reviews', 'Result 1 — location'],
            ['home.reviews.result1_before', '562', 'text', 'home_reviews', 'Result 1 — before score'],
            ['home.reviews.result1_gain', '+221 in 96 days', 'text', 'home_reviews', 'Result 1 — gain'],
            ['home.reviews.result2_emoji', '💼', 'text', 'home_reviews', 'Result 2 — emoji'],
            ['home.reviews.result2_quote', 'Went from being denied for everything to a $50K business line in under 60 days. Then another $35K in 0% APR cards.', 'textarea', 'home_reviews', 'Result 2 — quote'],
            ['home.reviews.result2_initials', 'MJ', 'text', 'home_reviews', 'Result 2 — initials'],
            ['home.reviews.result2_name', 'Marcus J.', 'text', 'home_reviews', 'Result 2 — name'],
            ['home.reviews.result2_loc', 'Houston, TX · Expedited + Business Funding', 'text', 'home_reviews', 'Result 2 — location'],
            ['home.reviews.result2_before', '582', 'text', 'home_reviews', 'Result 2 — before score'],
            ['home.reviews.result2_gain', '+208 in 47 days', 'text', 'home_reviews', 'Result 2 — gain'],
            ['home.reviews.result3_emoji', '🧾', 'text', 'home_reviews', 'Result 3 — emoji'],
            ['home.reviews.result3_quote', 'Six charge-offs deleted, two collections gone. Finally felt in control of my financial future.', 'textarea', 'home_reviews', 'Result 3 — quote'],
            ['home.reviews.result3_initials', 'DR', 'text', 'home_reviews', 'Result 3 — initials'],
            ['home.reviews.result3_name', 'Destiny R.', 'text', 'home_reviews', 'Result 3 — name'],
            ['home.reviews.result3_loc', 'Atlanta, GA · Full Credit Repair', 'text', 'home_reviews', 'Result 3 — location'],
            ['home.reviews.result3_before', '541', 'text', 'home_reviews', 'Result 3 — before score'],
            ['home.reviews.result3_gain', '+229 in 81 days', 'text', 'home_reviews', 'Result 3 — gain'],
            ['home.reviews.result4_emoji', '🚀', 'text', 'home_reviews', 'Result 4 — emoji'],
            ['home.reviews.result4_quote', 'My LLC, my EIN, my D&amp;B, all set up in under a week. Then $35K in business credit. Whole game changed.', 'html', 'home_reviews', 'Result 4 — quote'],
            ['home.reviews.result4_initials', 'TA', 'text', 'home_reviews', 'Result 4 — initials'],
            ['home.reviews.result4_name', 'Terrence A.', 'text', 'home_reviews', 'Result 4 — name'],
            ['home.reviews.result4_loc', 'Dallas, TX · Business Mentorship', 'text', 'home_reviews', 'Result 4 — location'],
            ['home.reviews.result4_before', '623', 'text', 'home_reviews', 'Result 4 — before score'],
            ['home.reviews.result4_gain', '+193 in 38 days', 'text', 'home_reviews', 'Result 4 — gain'],
            ['home.reviews.result5_emoji', '🚗', 'text', 'home_reviews', 'Result 5 — emoji'],
            ['home.reviews.result5_quote', 'Drove off the lot in a brand new SUV at 5.9% APR. Two months earlier I had been denied at three dealerships.', 'textarea', 'home_reviews', 'Result 5 — quote'],
            ['home.reviews.result5_initials', 'KW', 'text', 'home_reviews', 'Result 5 — initials'],
            ['home.reviews.result5_name', 'Kalen W.', 'text', 'home_reviews', 'Result 5 — name'],
            ['home.reviews.result5_loc', 'Phoenix, AZ · Standard 3-Round', 'text', 'home_reviews', 'Result 5 — location'],
            ['home.reviews.result5_before', '594', 'text', 'home_reviews', 'Result 5 — before score'],
            ['home.reviews.result5_gain', '+158 in 64 days', 'text', 'home_reviews', 'Result 5 — gain'],
            ['home.reviews.result6_emoji', '⚖️', 'text', 'home_reviews', 'Result 6 — emoji'],
            ['home.reviews.result6_quote', 'A bankruptcy from 2019 was finally removed. Plus three collections. Now we are pre-approved for a duplex.', 'textarea', 'home_reviews', 'Result 6 — quote'],
            ['home.reviews.result6_initials', 'MS', 'text', 'home_reviews', 'Result 6 — initials'],
            ['home.reviews.result6_name', 'Monica & Stephen S.', 'text', 'home_reviews', 'Result 6 — name'],
            ['home.reviews.result6_loc', 'Tampa, FL · Duo Full Repair', 'text', 'home_reviews', 'Result 6 — location'],
            ['home.reviews.result6_before', '498', 'text', 'home_reviews', 'Result 6 — before score'],
            ['home.reviews.result6_gain', '+248 in 110 days', 'text', 'home_reviews', 'Result 6 — gain'],
            ['home.reviews.results_disclaimer', 'Results vary by individual. Names anonymized for client privacy where requested.', 'textarea', 'home_reviews', 'Results — disclaimer'],
            ['home.reviews.reviews_eyebrow', 'Real Reviews', 'text', 'home_reviews', 'Reviews gallery — eyebrow'],
            ['home.reviews.reviews_heading', 'What our clients are actually saying.', 'text', 'home_reviews', 'Reviews gallery — heading'],
            ['home.reviews.reviews_sub', 'Real messages from real clients. These are people we have walked through credit repair, business structure, and funding.', 'textarea', 'home_reviews', 'Reviews gallery — subtitle'],
            ['home.reviews.gallery_caption', 'Tap any review to view full size. Names and photos shown with permission.', 'textarea', 'home_reviews', 'Reviews gallery — caption'],

            ['home.extra.compare_eyebrow', 'Why AQ Wealth University', 'text', 'home_extra', 'Compare — eyebrow'],
            ['home.extra.compare_heading', 'Why Other Companies<br/><span class="gold-text">Fall Short.</span>', 'html', 'home_extra', 'Compare — heading'],
            ['home.extra.compare_sub', 'Most companies send the same template letter for every client and call it a strategy. We built something different. Every dispute is targeted, every client has a dedicated advisor, and you see every move we make.', 'textarea', 'home_extra', 'Compare — subtitle'],
            ['home.extra.compare_feat1_num', '01 &nbsp;·&nbsp; Strategy', 'html', 'home_extra', 'Compare — feature 1 number'],
            ['home.extra.compare_feat1_title', 'Targeted Disputes, Not Template Letters', 'text', 'home_extra', 'Compare — feature 1 title'],
            ['home.extra.compare_feat1_desc', 'Every challenge we file is built around your specific violations. We go after items that are inaccurate, unverifiable, or legally reportable under the FCRA and FDCPA — not cookie-cutter letters bureaus routinely ignore.', 'textarea', 'home_extra', 'Compare — feature 1 description'],
            ['home.extra.compare_feat2_num', '02 &nbsp;·&nbsp; Transparency', 'html', 'home_extra', 'Compare — feature 2 number'],
            ['home.extra.compare_feat2_title', 'You Watch It Happen, in Real Time', 'text', 'home_extra', 'Compare — feature 2 title'],
            ['home.extra.compare_feat2_desc', 'Every dispute status, bureau response, and score update is visible in your client portal the moment it happens. You always know exactly what was filed, what came back, and what is next.', 'textarea', 'home_extra', 'Compare — feature 2 description'],
            ['home.extra.compare_feat3_num', '03 &nbsp;·&nbsp; Accountability', 'html', 'home_extra', 'Compare — feature 3 number'],
            ['home.extra.compare_feat3_title', 'One Advisor. Your Entire Journey.', 'text', 'home_extra', 'Compare — feature 3 title'],
            ['home.extra.compare_feat3_desc', 'The same advisor who reviews your file on day one handles your case through completion. No call centers, no re-explaining yourself, no shuffled files. One relationship from start to finish.', 'textarea', 'home_extra', 'Compare — feature 3 description'],
            ['home.extra.compare_feat4_num', '04 &nbsp;·&nbsp; Growth', 'html', 'home_extra', 'Compare — feature 4 number'],
            ['home.extra.compare_feat4_title', 'From Personal Credit to Business Funding', 'text', 'home_extra', 'Compare — feature 4 title'],
            ['home.extra.compare_feat4_desc', 'We do not stop at your personal score. While we repair your profile, we show you how to build business credit that stands on its own, structure your company correctly, and access capital without relying on your social.', 'textarea', 'home_extra', 'Compare — feature 4 description'],
            ['home.extra.compare_scroll_hint', '← Scroll to compare →', 'text', 'home_extra', 'Compare — mobile scroll hint'],
            ['home.extra.compare_th_feature', 'Feature', 'text', 'home_extra', 'Compare table — Feature header'],
            ['home.extra.compare_th_us', 'AQ Wealth Univ.', 'text', 'home_extra', 'Compare table — Us header'],
            ['home.extra.compare_th_them', 'Others', 'text', 'home_extra', 'Compare table — Them header'],
            ['home.extra.compare_row1', 'Personalized report review', 'text', 'home_extra', 'Compare table — row 1'],
            ['home.extra.compare_row2', 'FCRA / FDCPA-based strategy', 'text', 'home_extra', 'Compare table — row 2'],
            ['home.extra.compare_row3', 'Real-time client portal', 'text', 'home_extra', 'Compare table — row 3'],
            ['home.extra.compare_row4', 'Dedicated advisor (no rep switching)', 'text', 'home_extra', 'Compare table — row 4'],
            ['home.extra.compare_row5', 'Medical debt review', 'text', 'home_extra', 'Compare table — row 5'],
            ['home.extra.compare_row6', 'Credit-building roadmap included', 'text', 'home_extra', 'Compare table — row 6'],
            ['home.extra.compare_row7', 'Business credit guidance', 'text', 'home_extra', 'Compare table — row 7'],
            ['home.extra.compare_row8', 'Business funding education', 'text', 'home_extra', 'Compare table — row 8'],
            ['home.extra.compare_stat1_num', '500+', 'text', 'home_extra', 'Compare — stat 1 number'],
            ['home.extra.compare_stat1_label', 'Clients served', 'text', 'home_extra', 'Compare — stat 1 label'],
            ['home.extra.compare_stat2_num', '100+', 'text', 'home_extra', 'Compare — stat 2 number'],
            ['home.extra.compare_stat2_label', 'Avg. point increase', 'text', 'home_extra', 'Compare — stat 2 label'],
            ['home.extra.compare_stat3_num', '90d', 'text', 'home_extra', 'Compare — stat 3 number'],
            ['home.extra.compare_stat3_label', 'Average timeline', 'text', 'home_extra', 'Compare — stat 3 label'],
            ['home.extra.compare_cta_title', 'Ready to stop settling for generic?', 'text', 'home_extra', 'Compare — CTA title'],
            ['home.extra.compare_cta_desc', 'Schedule a free credit review. See exactly what is dragging your score down, and what we can do about it.', 'textarea', 'home_extra', 'Compare — CTA description'],
            ['home.extra.compare_cta_btn', 'Get My Free Review →', 'text', 'home_extra', 'Compare — CTA button'],

            ['home.extra.projector_eyebrow', 'Wealth Projector · Interactive', 'text', 'home_extra', 'Projector — eyebrow'],
            ['home.extra.projector_heading', 'See your future, <span class="gold-text">in real time.</span>', 'html', 'home_extra', 'Projector — heading'],
            ['home.extra.projector_sub', 'Move the sliders. Pick a package. Watch what your credit, savings, and funding could look like 90 days from now.', 'textarea', 'home_extra', 'Projector — subtitle'],
            ['home.extra.projector_label_score', 'Current Credit Score', 'text', 'home_extra', 'Projector — score slider label'],
            ['home.extra.projector_label_debt', 'Current Debt', 'text', 'home_extra', 'Projector — debt slider label'],
            ['home.extra.projector_label_package', 'Choose Your Package', 'text', 'home_extra', 'Projector — package label'],
            ['home.extra.projector_pkg_standard', 'Standard', 'text', 'home_extra', 'Projector — package Standard'],
            ['home.extra.projector_pkg_expedited', 'Expedited', 'text', 'home_extra', 'Projector — package Expedited'],
            ['home.extra.projector_pkg_premium', 'Premium', 'text', 'home_extra', 'Projector — package Premium'],
            ['home.extra.projector_disclaimer', 'Estimates only. Actual results vary by credit profile and market conditions.', 'textarea', 'home_extra', 'Projector — disclaimer'],
            ['home.extra.projector_result_label', 'Projected Score · 90 Days', 'text', 'home_extra', 'Projector — result label'],
            ['home.extra.projector_stat1_label', 'Lifetime Loan Savings', 'text', 'home_extra', 'Projector — stat 1 label'],
            ['home.extra.projector_stat2_label', 'Funding Capacity', 'text', 'home_extra', 'Projector — stat 2 label'],
            ['home.extra.projector_stat3_label', 'Better APR', 'text', 'home_extra', 'Projector — stat 3 label'],
            ['home.extra.projector_cta', 'Make This Real →', 'text', 'home_extra', 'Projector — CTA'],

            ['home.mentorship.eyebrow', 'Mentorship', 'text', 'home_mentorship', 'Mentorship — eyebrow'],
            ['home.mentorship.heading', 'Learn it. Own it. Teach it.', 'text', 'home_mentorship', 'Mentorship — heading'],
            ['home.mentorship.sub', 'Get into private mentorship with our team. Learn how to repair credit and structure businesses for yourself, for your family, or as a service you can charge real money for.', 'textarea', 'home_mentorship', 'Mentorship — subtitle'],
            ['home.mentorship.card1_label', 'Credit Repair Mentorship', 'text', 'home_mentorship', 'Mentorship — card 1 label'],
            ['home.mentorship.card1_title', 'Master the Credit Repair Process', 'text', 'home_mentorship', 'Mentorship — card 1 title'],
            ['home.mentorship.card1_desc', 'Learn how to dispute, delete, rebuild, and turn credit knowledge into income. We hand you the exact systems we use on clients every day.', 'textarea', 'home_mentorship', 'Mentorship — card 1 description'],
            ['home.mentorship.card1_feat1', 'Full dispute & deletion playbook', 'text', 'home_mentorship', 'Mentorship — card 1 feature 1'],
            ['home.mentorship.card1_feat2', 'Client onboarding & systems', 'text', 'home_mentorship', 'Mentorship — card 1 feature 2'],
            ['home.mentorship.card1_feat3', 'Pricing, packaging & sales scripts', 'text', 'home_mentorship', 'Mentorship — card 1 feature 3'],
            ['home.mentorship.card1_feat4', 'Direct mentorship with our team', 'text', 'home_mentorship', 'Mentorship — card 1 feature 4'],
            ['home.mentorship.card1_price', '$3,500', 'text', 'home_mentorship', 'Mentorship — card 1 price'],
            ['home.mentorship.card1_cta', 'Apply Now', 'text', 'home_mentorship', 'Mentorship — card 1 CTA'],
            ['home.mentorship.card2_label', 'Business Mentorship', 'text', 'home_mentorship', 'Mentorship — card 2 label'],
            ['home.mentorship.card2_title', 'Structure & Scale Your Business', 'text', 'home_mentorship', 'Mentorship — card 2 title'],
            ['home.mentorship.card2_desc', 'From LLC formation to business credit to stacking funding, we walk you through every step of building a real, fundable business.', 'textarea', 'home_mentorship', 'Mentorship — card 2 description'],
            ['home.mentorship.card2_feat1', 'LLC, EIN & banking setup', 'text', 'home_mentorship', 'Mentorship — card 2 feature 1'],
            ['home.mentorship.card2_feat2', 'Business credit profile build-out', 'text', 'home_mentorship', 'Mentorship — card 2 feature 2'],
            ['home.mentorship.card2_feat3', 'Funding stack & lender strategy', 'text', 'home_mentorship', 'Mentorship — card 2 feature 3'],
            ['home.mentorship.card2_feat4', '1:1 strategy sessions', 'text', 'home_mentorship', 'Mentorship — card 2 feature 4'],
            ['home.mentorship.card2_price', '$1,500', 'text', 'home_mentorship', 'Mentorship — card 2 price'],
            ['home.mentorship.card2_cta', 'Apply Now', 'text', 'home_mentorship', 'Mentorship — card 2 CTA'],

            ['home.business.eyebrow', 'Business Setup · Done Right', 'text', 'home_business', 'Business — eyebrow'],
            ['home.business.heading', 'Build a <span class="gold-text">Fundable &amp; Profitable</span> Business Structure.', 'html', 'home_business', 'Business — heading'],
            ['home.business.intro', 'The <strong>Business Blueprint Mentorship</strong> is designed for aspiring entrepreneurs who want to <strong>launch their own business with a solid, fundable foundation</strong>. This program equips you with the tools, strategies, and guidance needed to create a <strong>professional, lender-ready business structure</strong> that can grow and scale successfully.', 'html', 'home_business', 'Business — intro paragraph'],
            ['home.business.bullet1', 'Lender-ready from day one', 'text', 'home_business', 'Business — bullet 1'],
            ['home.business.bullet2', 'Scalable, professional foundation', 'text', 'home_business', 'Business — bullet 2'],
            ['home.business.cta_primary', 'Start My Blueprint →', 'text', 'home_business', 'Business — primary CTA (checkout)'],
            ['home.business.cta_primary_alt', 'Apply for the Blueprint →', 'text', 'home_business', 'Business — primary CTA (fallback)'],
            ['home.business.cta_secondary', 'Talk to an Advisor', 'text', 'home_business', 'Business — secondary CTA'],
            ['home.business.learn_eyebrow', 'What You&rsquo;ll Learn &amp; Receive', 'html', 'home_business', 'Business — learn card eyebrow'],
            ['home.business.learn_title', 'Fundable Business Structure', 'text', 'home_business', 'Business — learn card title'],
            ['home.business.item1', 'Establish a <strong>Professional Business Address</strong>', 'html', 'home_business', 'Business — checklist item 1'],
            ['home.business.item2', 'Form your <strong>LLC or Corporation</strong>', 'html', 'home_business', 'Business — checklist item 2'],
            ['home.business.item3', 'Obtain a <strong>Federal EIN</strong>', 'html', 'home_business', 'Business — checklist item 3'],
            ['home.business.item4', 'Secure a <strong>D-U-N-S Number</strong> for credit and funding purposes', 'html', 'home_business', 'Business — checklist item 4'],
            ['home.business.item5', 'Set up a <strong>Business Email and Phone Number</strong>', 'html', 'home_business', 'Business — checklist item 5'],
            ['home.business.item6', 'Create a <strong>Professional Website and Branding</strong>', 'html', 'home_business', 'Business — checklist item 6'],
            ['home.business.item7', '…and more', 'text', 'home_business', 'Business — checklist item 7'],
            ['home.business.signature', '&mdash; Danielle Todd<br/><span class="text-xs not-italic uppercase tracking-widest" style="color:#7a5707;">CEO · AQ Wealth University</span>', 'html', 'home_business', 'Business — signature block'],
            ['home.business.card_cta', 'Get Started →', 'text', 'home_business', 'Business — card CTA (checkout)'],
            ['home.business.card_cta_alt', 'Apply Now', 'text', 'home_business', 'Business — card CTA (fallback)'],

            ['home.extra.process_eyebrow', 'How It Works', 'text', 'home_extra', 'Process — eyebrow'],
            ['home.extra.process_heading', 'A clear path from where you are to where you\'re going.', 'text', 'home_extra', 'Process — heading'],
            ['home.extra.step1_title', 'Apply', 'text', 'home_extra', 'Process — step 1 title'],
            ['home.extra.step1_desc', 'Tell us where you are with credit, business, and funding. Free intake.', 'textarea', 'home_extra', 'Process — step 1 description'],
            ['home.extra.step1_time', '~5 minutes', 'text', 'home_extra', 'Process — step 1 time'],
            ['home.extra.step2_title', 'Strategize', 'text', 'home_extra', 'Process — step 2 title'],
            ['home.extra.step2_desc', 'We design the exact package and roadmap for your goals and timeline.', 'textarea', 'home_extra', 'Process — step 2 description'],
            ['home.extra.step2_time', '1–2 days', 'text', 'home_extra', 'Process — step 2 time'],
            ['home.extra.step3_title', 'Execute', 'text', 'home_extra', 'Process — step 3 title'],
            ['home.extra.step3_desc', 'Disputes filed, structure set up, funding pursued, with you in the loop the whole way.', 'textarea', 'home_extra', 'Process — step 3 description'],
            ['home.extra.step3_time', '14–90 days', 'text', 'home_extra', 'Process — step 3 time'],
            ['home.extra.step4_title', 'Elevate', 'text', 'home_extra', 'Process — step 4 title'],
            ['home.extra.step4_desc', 'You leave with clean credit, a fundable business, and the knowledge to stay there.', 'textarea', 'home_extra', 'Process — step 4 description'],
            ['home.extra.step4_time', 'Lifetime', 'text', 'home_extra', 'Process — step 4 time'],

            ['home.faq.eyebrow', 'FAQ', 'text', 'home_faq', 'FAQ — eyebrow'],
            ['home.faq.heading', 'Questions, answered.', 'text', 'home_faq', 'FAQ — heading'],
            ['home.faq.q1', 'How fast will I see results from credit repair?', 'text', 'home_faq', 'FAQ — question 1'],
            ['home.faq.a1', 'Standard 3-Round packages typically deliver visible results in 30–90 days. Our Expedited packages are designed to deliver results in as little as 14–30 days.', 'textarea', 'home_faq', 'FAQ — answer 1'],
            ['home.faq.q2', 'What\'s the difference between Single and Duo?', 'text', 'home_faq', 'FAQ — question 2'],
            ['home.faq.a2', 'Single covers one person. Duo lets you bring a partner (spouse, family member, or business partner) at a reduced combined rate. Same scope of work for both profiles.', 'textarea', 'home_faq', 'FAQ — answer 2'],
            ['home.faq.q3', 'Do I need credit repair before business credit?', 'text', 'home_faq', 'FAQ — question 3'],
            ['home.faq.a3', 'Not always. Business credit can be built independently, but personal credit strengthens your funding capacity. We\'ll map the right sequence on your strategy call.', 'textarea', 'home_faq', 'FAQ — answer 3'],
            ['home.faq.q4', 'What does the $99/month community include?', 'text', 'home_faq', 'FAQ — question 4'],
            ['home.faq.a4', 'Live trainings, frameworks, replays, and direct access to the AQ Wealth network. It\'s the easiest way to keep learning and stay sharp every month.', 'textarea', 'home_faq', 'FAQ — answer 4'],
            ['home.faq.q5', 'Is mentorship right for me?', 'text', 'home_faq', 'FAQ — question 5'],
            ['home.faq.a5', 'Mentorship is for people who are serious about either building a credit repair business of their own, or really mastering business structure and funding for themselves. Apply and we\'ll talk to see if it\'s a fit.', 'textarea', 'home_faq', 'FAQ — answer 5'],

            ['home.extra.contact_eyebrow', 'Free Credit Review', 'text', 'home_extra', 'Contact — eyebrow'],
            ['home.extra.contact_heading', 'Apply for credit repair<br/><span class="gold-text">in five minutes.</span>', 'html', 'home_extra', 'Contact — heading'],
            ['home.extra.contact_sub', 'Tell us where you\'re at. We\'ll review your situation and reach out within one business day with a custom plan and pricing.', 'textarea', 'home_extra', 'Contact — subtitle'],
            ['home.extra.contact_form_title', 'Free Credit Review', 'text', 'home_extra', 'Contact — form title'],
            ['home.extra.contact_form_sub', 'A senior advisor will reach out within one business day.', 'text', 'home_extra', 'Contact — form subtitle'],
            ['home.extra.contact_label_name', 'Full Name <span class="req">*</span>', 'html', 'home_extra', 'Contact — Full Name label'],
            ['home.extra.contact_label_email', 'Email Address <span class="req">*</span>', 'html', 'home_extra', 'Contact — Email label'],
            ['home.extra.contact_label_phone', 'Phone Number <span class="req">*</span>', 'html', 'home_extra', 'Contact — Phone label'],
            ['home.extra.contact_submit', 'Request My Free Review', 'text', 'home_extra', 'Contact — submit button'],
            ['home.extra.contact_success_title', 'You\'re in.', 'text', 'home_extra', 'Contact — success title'],
            ['home.extra.contact_success_text', 'A senior advisor will reach out within one business day.', 'text', 'home_extra', 'Contact — success text'],
            ['home.extra.trust1', '256-bit SSL', 'text', 'home_extra', 'Contact — trust badge 1'],
            ['home.extra.trust2', 'No spam, ever', 'text', 'home_extra', 'Contact — trust badge 2'],
            ['home.extra.trust3', 'Private &amp; secure', 'text', 'home_extra', 'Contact — trust badge 3'],

            ['home.extra.footer_explore_heading', 'Explore', 'text', 'home_extra', 'Footer — Explore heading'],
            ['home.extra.footer_contact_heading', 'Contact', 'text', 'home_extra', 'Footer — Contact heading'],
            ['home.extra.footer_email_label', 'Email:', 'text', 'home_extra', 'Footer — Email label'],
            ['home.extra.footer_hours_label', 'Hours:', 'text', 'home_extra', 'Footer — Hours label'],
            ['home.extra.footer_rights', 'All rights reserved.', 'text', 'home_extra', 'Footer — rights text'],

            ['home.extra.quiz_step1_num', 'Step 1 of 5', 'text', 'home_extra', 'Quiz — step 1 number'],
            ['home.extra.quiz_step1_question', 'What\'s your biggest credit challenge right now?', 'text', 'home_extra', 'Quiz — step 1 question'],
            ['home.extra.quiz_step1_opt1', 'Collections &amp; Charge-offs', 'html', 'home_extra', 'Quiz — step 1 option 1'],
            ['home.extra.quiz_step1_opt2', 'Late Payments', 'text', 'home_extra', 'Quiz — step 1 option 2'],
            ['home.extra.quiz_step1_opt3', 'Student Loans', 'text', 'home_extra', 'Quiz — step 1 option 3'],
            ['home.extra.quiz_step1_opt4', 'Bankruptcy or Foreclosure', 'text', 'home_extra', 'Quiz — step 1 option 4'],
            ['home.extra.quiz_step1_opt5', 'Not Sure / Multiple Issues', 'text', 'home_extra', 'Quiz — step 1 option 5'],
            ['home.extra.quiz_step2_num', 'Step 2 of 5', 'text', 'home_extra', 'Quiz — step 2 number'],
            ['home.extra.quiz_step2_question', 'What\'s your current credit score range?', 'text', 'home_extra', 'Quiz — step 2 question'],
            ['home.extra.quiz_step2_opt1', 'Below 500 (Poor)', 'text', 'home_extra', 'Quiz — step 2 option 1'],
            ['home.extra.quiz_step2_opt2', '500-579 (Very Poor)', 'text', 'home_extra', 'Quiz — step 2 option 2'],
            ['home.extra.quiz_step2_opt3', '580-669 (Fair)', 'text', 'home_extra', 'Quiz — step 2 option 3'],
            ['home.extra.quiz_step2_opt4', '670-739 (Good)', 'text', 'home_extra', 'Quiz — step 2 option 4'],
            ['home.extra.quiz_step2_opt5', 'I Don\'t Know', 'text', 'home_extra', 'Quiz — step 2 option 5'],
            ['home.extra.quiz_step3_num', 'Step 3 of 5', 'text', 'home_extra', 'Quiz — step 3 number'],
            ['home.extra.quiz_step3_question', 'How many negative items are on your credit report?', 'text', 'home_extra', 'Quiz — step 3 question'],
            ['home.extra.quiz_step3_opt1', '1-3 Items', 'text', 'home_extra', 'Quiz — step 3 option 1'],
            ['home.extra.quiz_step3_opt2', '4-7 Items', 'text', 'home_extra', 'Quiz — step 3 option 2'],
            ['home.extra.quiz_step3_opt3', '8-15 Items', 'text', 'home_extra', 'Quiz — step 3 option 3'],
            ['home.extra.quiz_step3_opt4', '15+ Items', 'text', 'home_extra', 'Quiz — step 3 option 4'],
            ['home.extra.quiz_step3_opt5', 'I Don\'t Know', 'text', 'home_extra', 'Quiz — step 3 option 5'],
            ['home.extra.quiz_step4_num', 'Step 4 of 5', 'text', 'home_extra', 'Quiz — step 4 number'],
            ['home.extra.quiz_step4_question', 'What\'s your main goal for improving your credit?', 'text', 'home_extra', 'Quiz — step 4 question'],
            ['home.extra.quiz_step4_opt1', 'Buy a Home or Refinance', 'text', 'home_extra', 'Quiz — step 4 option 1'],
            ['home.extra.quiz_step4_opt2', 'Get a Car Loan', 'text', 'home_extra', 'Quiz — step 4 option 2'],
            ['home.extra.quiz_step4_opt3', 'Start or Grow My Business', 'text', 'home_extra', 'Quiz — step 4 option 3'],
            ['home.extra.quiz_step4_opt4', 'Access Personal Funding', 'text', 'home_extra', 'Quiz — step 4 option 4'],
            ['home.extra.quiz_step4_opt5', 'Peace of Mind &amp; Fresh Start', 'html', 'home_extra', 'Quiz — step 4 option 5'],
            ['home.extra.quiz_step5_num', 'Step 5 of 5', 'text', 'home_extra', 'Quiz — step 5 number'],
            ['home.extra.quiz_step5_question', 'Get Your Free Credit Analysis', 'text', 'home_extra', 'Quiz — step 5 question'],
            ['home.extra.quiz_back', '← Back', 'text', 'home_extra', 'Quiz — back button'],
            ['home.extra.quiz_submit', 'Get My Free Analysis', 'text', 'home_extra', 'Quiz — submit button'],
            ['home.extra.quiz_success_title', 'You\'re in.', 'text', 'home_extra', 'Quiz — success title'],
            ['home.extra.quiz_success_text', 'Your credit analysis is on the way. A senior advisor will reach out within one business day with a custom plan.', 'textarea', 'home_extra', 'Quiz — success text'],
            ['home.extra.quiz_success_close', 'Close', 'text', 'home_extra', 'Quiz — success close button'],

            // ============================================================
            // FUNDING PAGE
            // ============================================================
            ['funding.announce_main', '<strong>Funding Available</strong> · Pre-qualify in under 5 minutes', 'html', 'funding', 'Funding — announcement main'],
            ['funding.announce_sub', 'Soft pull, no impact on your credit', 'text', 'funding', 'Funding — announcement sub'],
            ['funding.nav_services', 'Services', 'text', 'funding', 'Funding — nav: Services'],
            ['funding.nav_pricing', 'Pricing', 'text', 'funding', 'Funding — nav: Pricing'],
            ['funding.nav_mentorship', 'Mentorship', 'text', 'funding', 'Funding — nav: Mentorship'],
            ['funding.nav_business_setup', 'Business Setup', 'text', 'funding', 'Funding — nav: Business Setup'],
            ['funding.nav_funding', 'Funding', 'text', 'funding', 'Funding — nav: Funding'],
            ['funding.nav_faq', 'FAQ', 'text', 'funding', 'Funding — nav: FAQ'],
            ['funding.nav_apply_cta', 'Apply Now', 'text', 'funding', 'Funding — nav Apply Now button'],
            ['funding.hero_badge', 'Now Funding Approvals', 'text', 'funding', 'Funding — hero badge'],
            ['funding.hero_title', 'Get <span class="gold-text">Funded.</span><br/>Without the Run-Around.', 'html', 'funding', 'Funding — hero title'],
            ['funding.hero_subtitle', 'Lines of credit, term loans, SBA-backed financing, equipment funding, and 0% APR business credit cards. Pre-qualify in under 5 minutes with a soft pull that does not affect your credit.', 'textarea', 'funding', 'Funding — hero subtitle'],
            ['funding.hero_cta_primary', 'Start My Application →', 'text', 'funding', 'Funding — hero primary CTA'],
            ['funding.hero_cta_secondary', 'See Funding Options', 'text', 'funding', 'Funding — hero secondary CTA'],
            ['funding.hero_stat1_value', '$250K+', 'text', 'funding', 'Funding — hero stat 1 value'],
            ['funding.hero_stat1_label', 'Max funding', 'text', 'funding', 'Funding — hero stat 1 label'],
            ['funding.hero_stat2_value', '24h', 'text', 'funding', 'Funding — hero stat 2 value'],
            ['funding.hero_stat2_label', 'Initial response', 'text', 'funding', 'Funding — hero stat 2 label'],
            ['funding.hero_stat3_value', '0%', 'text', 'funding', 'Funding — hero stat 3 value'],
            ['funding.hero_stat3_label', 'Intro APR options', 'text', 'funding', 'Funding — hero stat 3 label'],
            ['funding.hero_stat4_value', 'Soft', 'text', 'funding', 'Funding — hero stat 4 value'],
            ['funding.hero_stat4_label', 'Credit pull', 'text', 'funding', 'Funding — hero stat 4 label'],
            ['funding.types_eyebrow', 'Funding Programs', 'text', 'funding', 'Funding — types eyebrow'],
            ['funding.types_title', 'Real funding products. Real lender networks.', 'text', 'funding', 'Funding — types title'],
            ['funding.types_sub', 'We work with a network of business-focused lenders, traditional and alternative, to match you with the funding product that actually fits where you are.', 'textarea', 'funding', 'Funding — types subtitle'],
            ['funding.type1_title', 'Business Lines of Credit', 'text', 'funding', 'Funding — type 1 title'],
            ['funding.type1_desc', 'Revolving credit you can draw, repay, and reuse. Ideal for working capital, payroll gaps, and unexpected expenses.', 'textarea', 'funding', 'Funding — type 1 desc'],
            ['funding.type1_amount_label', 'Up to', 'text', 'funding', 'Funding — type 1 amount label'],
            ['funding.type1_amount_val', '$250,000', 'text', 'funding', 'Funding — type 1 amount value'],
            ['funding.type2_title', 'Term Loans', 'text', 'funding', 'Funding — type 2 title'],
            ['funding.type2_desc', 'Lump-sum financing with predictable monthly payments. Great for expansion, equipment, or large one-time investments.', 'textarea', 'funding', 'Funding — type 2 desc'],
            ['funding.type2_amount_label', 'Up to', 'text', 'funding', 'Funding — type 2 amount label'],
            ['funding.type2_amount_val', '$500,000', 'text', 'funding', 'Funding — type 2 amount value'],
            ['funding.type3_title', 'SBA Loans', 'text', 'funding', 'Funding — type 3 title'],
            ['funding.type3_desc', 'Government-backed loans with extended terms and competitive rates. Best for established businesses with solid financials.', 'textarea', 'funding', 'Funding — type 3 desc'],
            ['funding.type3_amount_label', 'Up to', 'text', 'funding', 'Funding — type 3 amount label'],
            ['funding.type3_amount_val', '$5M', 'text', 'funding', 'Funding — type 3 amount value'],
            ['funding.type4_title', 'Equipment Financing', 'text', 'funding', 'Funding — type 4 title'],
            ['funding.type4_desc', 'Finance the equipment you need with the equipment itself as collateral. Trucks, machinery, computers, kitchen gear.', 'textarea', 'funding', 'Funding — type 4 desc'],
            ['funding.type4_amount_label', 'Up to', 'text', 'funding', 'Funding — type 4 amount label'],
            ['funding.type4_amount_val', '$1M', 'text', 'funding', 'Funding — type 4 amount value'],
            ['funding.type5_title', '0% APR Business Credit', 'text', 'funding', 'Funding — type 5 title'],
            ['funding.type5_desc', 'Stack 0% intro APR business credit cards for short-term capital. Build business credit and earn rewards while you scale.', 'textarea', 'funding', 'Funding — type 5 desc'],
            ['funding.type5_amount_label', 'Up to', 'text', 'funding', 'Funding — type 5 amount label'],
            ['funding.type5_amount_val', '$150,000', 'text', 'funding', 'Funding — type 5 amount value'],
            ['funding.type6_title', 'Invoice Factoring', 'text', 'funding', 'Funding — type 6 title'],
            ['funding.type6_desc', 'Turn outstanding invoices into immediate cash. Sell receivables to a factor and receive 80–90% upfront, no debt added.', 'textarea', 'funding', 'Funding — type 6 desc'],
            ['funding.type6_amount_label', 'Advance rate', 'text', 'funding', 'Funding — type 6 amount label'],
            ['funding.type6_amount_val', 'Up to 90%', 'text', 'funding', 'Funding — type 6 amount value'],
            ['funding.req_eyebrow', 'Requirements', 'text', 'funding', 'Funding — requirements eyebrow'],
            ['funding.req_title', 'What you\'ll need to qualify.', 'text', 'funding', 'Funding — requirements title'],
            ['funding.req_sub', 'Most clients qualify if they meet the baseline below. Don\'t qualify yet? We\'ll walk you through credit repair and business setup so you do.', 'textarea', 'funding', 'Funding — requirements subtitle'],
            ['funding.req1_title', 'Personal credit score 600+', 'text', 'funding', 'Funding — req 1 title'],
            ['funding.req1_desc', 'Some products go lower with collateral or revenue', 'text', 'funding', 'Funding — req 1 desc'],
            ['funding.req2_title', 'Registered business entity (LLC, Corp, etc.)', 'text', 'funding', 'Funding — req 2 title'],
            ['funding.req2_desc', 'Need help forming one? We do that too', 'text', 'funding', 'Funding — req 2 desc'],
            ['funding.req3_title', 'EIN and business bank account', 'text', 'funding', 'Funding — req 3 title'],
            ['funding.req3_desc', 'Separate from personal finances', 'text', 'funding', 'Funding — req 3 desc'],
            ['funding.req4_title', 'U.S.-based business operations', 'text', 'funding', 'Funding — req 4 title'],
            ['funding.req4_desc', 'All 50 states served', 'text', 'funding', 'Funding — req 4 desc'],
            ['funding.req5_title', 'Last 3 months of bank statements (for revenue products)', 'text', 'funding', 'Funding — req 5 title'],
            ['funding.req5_desc', 'Not required for personal-credit-only programs', 'text', 'funding', 'Funding — req 5 desc'],
            ['funding.process_eyebrow', 'How It Works', 'text', 'funding', 'Funding — process eyebrow'],
            ['funding.process_title', 'Three steps to funding.', 'text', 'funding', 'Funding — process title'],
            ['funding.process_sub', 'A simple, transparent process. No hidden fees, no surprise paperwork, no pressure.', 'textarea', 'funding', 'Funding — process subtitle'],
            ['funding.step1_num', '01', 'text', 'funding', 'Funding — step 1 number'],
            ['funding.step1_title', 'Pre-Qualify', 'text', 'funding', 'Funding — step 1 title'],
            ['funding.step1_desc', 'Fill out the application below. Soft credit pull only, takes about 5 minutes. We see what you qualify for in real time.', 'textarea', 'funding', 'Funding — step 1 desc'],
            ['funding.step2_num', '02', 'text', 'funding', 'Funding — step 2 number'],
            ['funding.step2_title', 'Match & Strategize', 'text', 'funding', 'Funding — step 2 title'],
            ['funding.step2_desc', 'We review your file, match you with the right lender(s), and walk you through the offers. You choose what fits.', 'textarea', 'funding', 'Funding — step 2 desc'],
            ['funding.step3_num', '03', 'text', 'funding', 'Funding — step 3 number'],
            ['funding.step3_title', 'Fund & Deploy', 'text', 'funding', 'Funding — step 3 title'],
            ['funding.step3_desc', 'Sign the offer, get funded, and put the capital to work. Most products fund in 2–10 business days from approval.', 'textarea', 'funding', 'Funding — step 3 desc'],
            ['funding.apply_eyebrow', 'Pre-Qualification', 'text', 'funding', 'Funding — apply eyebrow'],
            ['funding.apply_title', 'Apply for funding.', 'text', 'funding', 'Funding — apply title'],
            ['funding.apply_sub', 'Five minutes. Soft pull. No impact on your credit. We\'ll review and reach out within 24 hours.', 'textarea', 'funding', 'Funding — apply subtitle'],
            ['funding.stepper1_label', 'Business', 'text', 'funding', 'Funding — stepper 1 label'],
            ['funding.stepper2_label', 'Financials', 'text', 'funding', 'Funding — stepper 2 label'],
            ['funding.stepper3_label', 'Contact', 'text', 'funding', 'Funding — stepper 3 label'],
            ['funding.panel1_title', 'Tell us about your business.', 'text', 'funding', 'Funding — panel 1 title'],
            ['funding.panel1_sub', 'Quick basics about your company so we can match you with the right lenders.', 'textarea', 'funding', 'Funding — panel 1 subtitle'],
            ['funding.field_biz_name_label', 'Legal Business Name <span class="req">*</span>', 'html', 'funding', 'Funding — field: Legal Business Name label'],
            ['funding.field_entity_label', 'Entity Type <span class="req">*</span>', 'html', 'funding', 'Funding — field: Entity Type label'],
            ['funding.field_industry_label', 'Industry <span class="req">*</span>', 'html', 'funding', 'Funding — field: Industry label'],
            ['funding.field_tib_label', 'Time in Business <span class="req">*</span>', 'html', 'funding', 'Funding — field: Time in Business label'],
            ['funding.field_state_label', 'State <span class="req">*</span>', 'html', 'funding', 'Funding — field: State label'],
            ['funding.btn_back', 'Back', 'text', 'funding', 'Funding — form Back button'],
            ['funding.btn_continue', 'Continue →', 'text', 'funding', 'Funding — form Continue button'],
            ['funding.panel2_title', 'Financials & funding need.', 'text', 'funding', 'Funding — panel 2 title'],
            ['funding.panel2_sub', 'This helps us match you with the right product. All figures are estimates, no documentation required at this stage.', 'textarea', 'funding', 'Funding — panel 2 subtitle'],
            ['funding.field_credit_label', 'Personal Credit Range <span class="req">*</span>', 'html', 'funding', 'Funding — field: Personal Credit Range label'],
            ['funding.field_revenue_label', 'Avg. Monthly Revenue <span class="req">*</span>', 'html', 'funding', 'Funding — field: Avg Monthly Revenue label'],
            ['funding.field_amount_label', 'Funding Amount Needed <span class="req">*</span>', 'html', 'funding', 'Funding — field: Funding Amount Needed label'],
            ['funding.field_funding_type_label', 'Funding Type Interest <span class="req">*</span>', 'html', 'funding', 'Funding — field: Funding Type Interest label'],
            ['funding.field_use_label', 'Use of Funds', 'text', 'funding', 'Funding — field: Use of Funds label'],
            ['funding.panel3_title', 'Where can we reach you?', 'text', 'funding', 'Funding — panel 3 title'],
            ['funding.panel3_sub', 'We\'ll review your application and get back to you within one business day with next steps.', 'textarea', 'funding', 'Funding — panel 3 subtitle'],
            ['funding.field_first_name_label', 'First Name <span class="req">*</span>', 'html', 'funding', 'Funding — field: First Name label'],
            ['funding.field_last_name_label', 'Last Name <span class="req">*</span>', 'html', 'funding', 'Funding — field: Last Name label'],
            ['funding.field_email_label', 'Email <span class="req">*</span>', 'html', 'funding', 'Funding — field: Email label'],
            ['funding.field_phone_label', 'Phone <span class="req">*</span>', 'html', 'funding', 'Funding — field: Phone label'],
            ['funding.field_besttime_label', 'Best Time to Connect', 'text', 'funding', 'Funding — field: Best Time to Connect label'],
            ['funding.consent_text', 'I authorize AQ Wealth University to contact me about my application and understand a soft credit pull may be performed. No hard pull occurs without my written consent.', 'textarea', 'funding', 'Funding — consent checkbox text'],
            ['funding.btn_submit', 'Submit Application →', 'text', 'funding', 'Funding — Submit Application button'],
            ['funding.success_title', 'Application received.', 'text', 'funding', 'Funding — success title'],
            ['funding.success_desc', 'Thank you. Your pre-qualification is in our hands. A funding advisor will reach out within one business day with your offers and next steps.', 'textarea', 'funding', 'Funding — success desc'],
            ['funding.success_cta', 'Back to Home', 'text', 'funding', 'Funding — success CTA'],
            ['funding.trust1', '256-bit SSL encrypted', 'text', 'funding', 'Funding — trust item 1'],
            ['funding.trust2', 'Soft pull, no credit impact', 'text', 'funding', 'Funding — trust item 2'],
            ['funding.trust3', 'Your info stays private', 'text', 'funding', 'Funding — trust item 3'],
            ['funding.footer_tagline', 'From knowledge to wisdom. From wisdom to wealth.', 'text', 'funding', 'Funding — footer tagline'],
            ['funding.footer_explore_heading', 'Explore', 'text', 'funding', 'Funding — footer Explore heading'],
            ['funding.footer_legal_heading', 'Legal', 'text', 'funding', 'Funding — footer Legal heading'],
            ['funding.footer_legal_text', 'AQ Wealth University. All rights reserved. AQ Wealth University is not a lender. We connect qualified applicants with third-party lenders. Funding terms, rates, and approvals are determined by the lender, not AQ Wealth University. Results vary by individual.', 'textarea', 'funding', 'Funding — footer legal text'],

            // ============================================================
            // INTAKE PAGE
            // ============================================================
            ['intake.eyebrow', 'Client Intake', 'text', 'intake', 'Intake — eyebrow label'],
            ['intake.title', 'Welcome to your <em>credit repair journey</em>.', 'html', 'intake', 'Intake — page title'],
            ['intake.subtitle', 'Thanks for taking the first step. Please complete this short intake so we can verify your information, prep your file, and send you the client agreement and onboarding next steps. Every detail matters &mdash; please double-check before submitting.', 'html', 'intake', 'Intake — intro paragraph'],
            ['intake.label_full_name', 'Full Legal Name', 'text', 'intake', 'Intake — Full Legal Name label'],
            ['intake.label_email', 'Email', 'text', 'intake', 'Intake — Email label'],
            ['intake.label_phone', 'Phone', 'text', 'intake', 'Intake — Phone label'],
            ['intake.label_dob', 'Date of Birth', 'text', 'intake', 'Intake — Date of Birth label'],
            ['intake.label_address', 'Mailing Address', 'text', 'intake', 'Intake — Mailing Address label'],
            ['intake.label_city', 'City', 'text', 'intake', 'Intake — City label'],
            ['intake.label_state', 'State', 'text', 'intake', 'Intake — State label'],
            ['intake.label_zip', 'ZIP', 'text', 'intake', 'Intake — ZIP label'],
            ['intake.label_ssn_last4', 'Last 4 of SSN', 'text', 'intake', 'Intake — Last 4 of SSN label'],
            ['intake.label_package', 'Package Purchased', 'text', 'intake', 'Intake — Package Purchased label'],
            ['intake.label_best_time', 'Best Time to Reach You', 'text', 'intake', 'Intake — Best Time label'],
            ['intake.label_goal', 'Your Main Credit Goal', 'text', 'intake', 'Intake — Main Credit Goal label'],
            ['intake.consent', 'I confirm the information above is accurate and authorize AQ Wealth University to contact me by phone, text, and email about my account. I understand my client agreement will be sent to the email above for review and signature.', 'textarea', 'intake', 'Intake — consent text'],
            ['intake.submit', 'Submit Intake &amp; Send My Agreement', 'html', 'intake', 'Intake — submit button'],
            ['intake.success_title', 'You\'re in.', 'text', 'intake', 'Intake — success heading'],
            ['intake.success_message', 'We\'ve received your intake. Check your inbox &mdash; your <strong>client agreement</strong> and onboarding instructions are on the way. If you don\'t see it within a few minutes, check your spam folder.', 'html', 'intake', 'Intake — success message'],
            ['intake.footer_note', '256-bit SSL · Your information is private and secure.', 'text', 'intake', 'Intake — footer security note'],

            // ============================================================
            // ONBOARDING PAGE
            // ============================================================
            ['onboarding.eyebrow', 'Client Onboarding', 'text', 'onboarding', 'Onboarding — hero eyebrow'],
            ['onboarding.title', 'Welcome to Your <em>Credit Repair Journey</em>', 'html', 'onboarding', 'Onboarding — hero title'],
            ['onboarding.intro', 'Congratulations on taking the first step toward reclaiming your credit. Below are the <strong>3 onboarding steps</strong> required before your repair process officially begins. Please read each one carefully &mdash; every detail matters.', 'html', 'onboarding', 'Onboarding — intro paragraph'],
            ['onboarding.step1_eyebrow', 'Step One', 'text', 'onboarding', 'Onboarding — step 1 eyebrow'],
            ['onboarding.step1_title', 'Activate Credit Monitoring', 'text', 'onboarding', 'Onboarding — step 1 title'],
            ['onboarding.step1_desc', 'Sign up for credit monitoring so we can pull your three-bureau reports and start filing disputes. This is non-negotiable &mdash; without monitoring access, we cannot work your file.', 'html', 'onboarding', 'Onboarding — step 1 description'],
            ['onboarding.step1_cta', 'Activate Monitoring →', 'text', 'onboarding', 'Onboarding — step 1 CTA'],
            ['onboarding.step1_cta_placeholder', 'Link arrives by email', 'text', 'onboarding', 'Onboarding — step 1 CTA placeholder'],
            ['onboarding.step2_eyebrow', 'Step Two', 'text', 'onboarding', 'Onboarding — step 2 eyebrow'],
            ['onboarding.step2_title', 'Upload ID &amp; Proof of Address', 'html', 'onboarding', 'Onboarding — step 2 title'],
            ['onboarding.step2_desc', 'Reply to your onboarding email with a clear photo of your government-issued ID and a recent utility bill or bank statement (within the last 60 days) showing your current mailing address.', 'text', 'onboarding', 'Onboarding — step 2 description'],
            ['onboarding.step3_eyebrow', 'Step Three', 'text', 'onboarding', 'Onboarding — step 3 eyebrow'],
            ['onboarding.step3_title', 'Access Your Client Portal', 'text', 'onboarding', 'Onboarding — step 3 title'],
            ['onboarding.step3_desc', 'Once Steps 1 and 2 are complete, you will receive client portal access within 24&ndash;48 hours. From there, your journey officially begins. 💜', 'html', 'onboarding', 'Onboarding — step 3 description'],
            ['onboarding.step3_cta', 'Open Portal →', 'text', 'onboarding', 'Onboarding — step 3 CTA'],
            ['onboarding.important_title', 'Very Important Information', 'text', 'onboarding', 'Onboarding — important callout title'],
            ['onboarding.important_item1', 'Please ensure <strong>ALL required login credentials are correct</strong>. This is your responsibility &mdash; you will be held 100% accountable.', 'html', 'onboarding', 'Onboarding — important item 1'],
            ['onboarding.important_item2', 'Updates from the bureaus arrive every <strong>30 to 45 days</strong>. Please allow this timeframe before expecting changes.', 'html', 'onboarding', 'Onboarding — important item 2'],
            ['onboarding.important_item3', 'I\'ll personally check in with you <strong>every two weeks as a courtesy</strong> &mdash; not including weekends or holidays.', 'html', 'onboarding', 'Onboarding — important item 3'],
            ['onboarding.important_item4', 'Trust the process. Real results take time &mdash; consistency wins.', 'html', 'onboarding', 'Onboarding — important item 4'],
            ['onboarding.important_item5', 'There are <strong>NO REFUNDS.</strong>', 'html', 'onboarding', 'Onboarding — important item 5'],
            ['onboarding.agreement_section_title', 'Client Service Agreement', 'text', 'onboarding', 'Onboarding — agreement section title'],
            ['onboarding.agreement_intro', 'Please read the agreement below in full, then type your full legal name and sign in the box to authorize.', 'text', 'onboarding', 'Onboarding — agreement intro'],
            ['onboarding.agreement_h1', '1. Scope of Services', 'text', 'onboarding', 'Onboarding — agreement heading 1'],
            ['onboarding.agreement_p1', 'AQ Wealth University LLC ("Company") agrees to provide credit consulting and dispute services on behalf of the undersigned client ("Client"), including review of credit reports from Equifax, Experian, and TransUnion, identification of inaccurate or unverifiable items, and submission of dispute correspondence to the bureaus and/or furnishers in accordance with the Fair Credit Reporting Act (15 U.S.C. § 1681 et seq.) and the Credit Repair Organizations Act (15 U.S.C. § 1679 et seq.).', 'textarea', 'onboarding', 'Onboarding — agreement para 1'],
            ['onboarding.agreement_h2', '2. Client Responsibilities', 'text', 'onboarding', 'Onboarding — agreement heading 2'],
            ['onboarding.agreement_p2', 'Client agrees to (a) provide accurate personal information, (b) maintain active credit monitoring as directed in Step 01, (c) forward all bureau and creditor correspondence to Company within 5 business days of receipt, and (d) refrain from disputing items directly with the bureaus during the term of this engagement.', 'textarea', 'onboarding', 'Onboarding — agreement para 2'],
            ['onboarding.agreement_h3', '3. Term &amp; Fees', 'html', 'onboarding', 'Onboarding — agreement heading 3'],
            ['onboarding.agreement_p3', 'Fees are as quoted at the point of purchase and are <strong>non-refundable</strong> once services have begun. Client acknowledges that no specific outcome is guaranteed and that results vary based on the accuracy and verifiability of items on Client\'s credit profile. Bureau response cycles run <strong>30&ndash;45 days</strong>.', 'html', 'onboarding', 'Onboarding — agreement para 3'],
            ['onboarding.agreement_h4', '4. Cancellation', 'text', 'onboarding', 'Onboarding — agreement heading 4'],
            ['onboarding.agreement_p4a', 'Pursuant to the CROA, Client has the right to cancel this contract within 3 business days of signing without penalty by sending written notice to', 'textarea', 'onboarding', 'Onboarding — agreement para 4 (before email)'],
            ['onboarding.agreement_p4b', 'After 3 business days, all fees paid are earned and non-refundable.', 'textarea', 'onboarding', 'Onboarding — agreement para 4 (after email)'],
            ['onboarding.agreement_h5', '5. Authorization &amp; Limited Power of Attorney', 'html', 'onboarding', 'Onboarding — agreement heading 5'],
            ['onboarding.agreement_p5', 'Client authorizes Company to communicate with credit bureaus, furnishers, collection agencies, and creditors on Client\'s behalf for the limited purpose of disputing inaccurate, incomplete, or unverifiable items, and to receive copies of credit reports and correspondence related to such disputes.', 'textarea', 'onboarding', 'Onboarding — agreement para 5'],
            ['onboarding.agreement_h6', '6. Communication Consent', 'text', 'onboarding', 'Onboarding — agreement heading 6'],
            ['onboarding.agreement_p6', 'Client consents to receive calls, SMS messages, and emails from Company at the contact information provided for purposes of servicing this account. Standard message and data rates may apply. Client may opt out at any time by replying STOP.', 'textarea', 'onboarding', 'Onboarding — agreement para 6'],
            ['onboarding.agreement_h7', '7. Entire Agreement', 'text', 'onboarding', 'Onboarding — agreement heading 7'],
            ['onboarding.agreement_p7', 'This document, together with the intake form completed by Client, constitutes the entire agreement between the parties and supersedes any prior verbal or written representations.', 'textarea', 'onboarding', 'Onboarding — agreement para 7'],
            ['onboarding.sig_name_label', 'Full Legal Name (typed)', 'text', 'onboarding', 'Onboarding — signature name label'],
            ['onboarding.sig_date_label', 'Date', 'text', 'onboarding', 'Onboarding — signature date label'],
            ['onboarding.sig_here_label', 'Sign Here', 'text', 'onboarding', 'Onboarding — sign here label'],
            ['onboarding.sig_pad_hint', 'Sign with mouse, trackpad, or finger', 'text', 'onboarding', 'Onboarding — signature pad hint'],
            ['onboarding.sig_clear', 'Clear', 'text', 'onboarding', 'Onboarding — signature clear button'],
            ['onboarding.sig_submit', 'I Agree &amp; Sign', 'html', 'onboarding', 'Onboarding — submit button'],
            ['onboarding.signoff_help', 'If any step is unclear, simply reply to your onboarding email &mdash; we\'re here to help you get started the right way.', 'html', 'onboarding', 'Onboarding — signoff help line'],
            ['onboarding.signoff_closing', 'To your financial freedom,', 'text', 'onboarding', 'Onboarding — signoff closing'],
            ['onboarding.signoff_name', 'Danielle Todd', 'text', 'onboarding', 'Onboarding — signoff name'],
            ['onboarding.signoff_role', 'Founder · AQ Wealth University', 'text', 'onboarding', 'Onboarding — signoff role'],
            ['onboarding.success_title', 'You\'re <em>signed</em>.', 'html', 'onboarding', 'Onboarding — success title'],
            ['onboarding.success_body', 'Your client agreement has been received. A signed copy is on its way to your inbox. Now finish <strong style="color:#ecd17d;">Steps 01 and 02</strong> above, and we\'ll have your portal access ready within 24&ndash;48 hours.', 'html', 'onboarding', 'Onboarding — success body'],
            ['onboarding.success_cta', 'Activate Credit Monitoring →', 'text', 'onboarding', 'Onboarding — success CTA'],
        ];

        foreach ($rows as $i => $row) {
            [$key, $value, $type, $group, $label] = $row;

            $setting = Setting::firstOrNew(['key' => $key]);

            if (! $setting->exists) {
                // text/textarea render through escaped {{ }}, so decode entities
                // to avoid double-encoding; html renders through {!! !!} (kept raw).
                $setting->value = in_array($type, ['text', 'textarea'], true)
                    ? html_entity_decode($value, ENT_QUOTES | ENT_HTML5, 'UTF-8')
                    : $value;
            }

            $setting->type  = $type;
            $setting->group = $group;
            $setting->label = $label;
            $setting->sort  = 1000 + $i;
            $setting->save();
        }

        Setting::flushCache();
    }
}
